openapi: 3.0.3
info:
  title: Orders API
  version: 1.0.0
paths:
  /order:
    post:
      summary: Create a new order
      description: Create a new order
      operationId: addOrder
      requestBody:
        description: Create a new order
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
        required: true
      responses:
        "201":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "400":
          description: Invalid input

components:
  schemas:
    Order:
      type: object
      properties:
        quantity:
          type: integer
          format: int32
          example: 7
        productId:
          type: string
          example: "12345"
